server:
  port: 8130

spring:
  profiles:
    active: dev
  application:
    name: service-oss

  # 添加nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.6:8848

aliyun:
  oss:
    endpoint: bearfile
    keyId: LTAI5tLonsxrMnQetxPXXVLj
    keySecret: Lwl32M8FRBbgpJC8ifxzBWslT5aPCo
    bucketName: jrb-file-hejia