# 项目环境docker配置文件
version: "3.9"

services:
  JRBMySQL:
    image: mysql
    container_name: JRBMySQL
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: jrb123456
    networks:
      - JRBNet


networks:
  JRBNet: