# 项目环境docker配置文件
version: "3.9"

services:
  JRBMySQL:
    image: mysql
    container_name: JRBMySQL
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: jrb123456
    networks:
      - JRBNet

  JRBNginx:
    image: nginx
    container_name: JRBNginx
    ports:
      - "80:80"
    networks:
      - JRBNet

  JRBRedis:
    image: redis
    container_name: JRBRedis
    ports:
      - "6379:6379"
    networks:
      - JRBNet
  JRBNacos:
    image: nacos/nacos-server:2.0.3
    container_name: JRBNacos
    environment:
      PREFER_HOST_MODE: hostname
      SPRING_DATASOURCE_PLATFORM: mysql
      MODE: standalone
      MYSQL_SERVICE_HOST: JRBMySQL
      MYSQL_SERVICE_DB_NAME: nacos_config
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: jrb123456
      JVM_XMS: 512m
      JVM_MMS: 320m
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    networks:
      - JRBNet

networks:
  JRBNet: