server:
  port: 8110

spring:
  main:
    allow-circular-references: true
  profiles:
    active: dev
  application:
    name: service-core
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.12:3306/jrb_core?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: jrb123456
  # Redis连接配置
  data:
    redis:
      host: 192.168.1.12
      port: 6379
      database: 0
      # 最大等待时间，超时则抛出异常，否则请求一直等待
      timeout: 3000ms
      lettuce:
        pool:
          # 最大连接数，负值表示没有限制，默认8
          max-active: 20
          # 最大阻塞等待时间，负值表示没限制，默认-1
          max-wait: -1
          # 最大空闲连接，默认8
          max-idle: 8
          # 最小空闲连接，默认0
          min-idle: 0

  # 添加nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.12:8848

  rabbitmq:
    host: 192.168.1.12
    port: 5672
    virtual-host: /jrbhost
    username: admin
    password: 123456


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*.xml