server:
  port: 8110

spring:
  profiles:
    active: dev
  application:
    name: service-core
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.41.201:3306/jrb_core?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: jrb123456

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:org/hejia/jrb/core/mapper/xml/*.xml