server:
  port: 8120

spring:
  profiles:
    # 环境设置
    active: dev
  application:
    # 服务名
    name: service-sms

  # redis
  data:
    redis:
      host: 192.168.1.6
      port: 6379
      database: 0
      # 最大等待时间，超时则抛出异常，否则请求一直等待
      timeout: 3000ms
      lettuce:
        pool:
          # 最大连接数，负值表示没有限制，默认8
          max-active: 20
          # 最大阻塞等待时间，负值表示没限制，默认-1
          max-wait: -1
          # 最大空闲连接，默认8
          max-idle: 8
          # 最小空闲连接，默认0
          min-idle: 0

  # 添加nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.6:8848
#        username: jrb-nacos
#        password: jrb-nacos

# 阿里云短信
aliyun:
  sms:
    region-id: cn-hangzhou
    key-id: LTAI5tSn61zKFUNhr52TMVzN
    key-secret: FIenCW7BYR8TlPeEzp5CtgZHO2UHPf
    template-code: SMS_154950909
    sign-name: 阿里云短信测试
